name: Test Action

on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-commit
        run: pre-commit --version

